### ISSUE TITLE
launch the main URL?

### ISSUE THREAD

**Issue by fc-admin1** [LaravelDaily/Laravel-Demo-Support-Tickets#9]
Hello,
I am new in Laravel. 
After running "php artisan serve" (it opens http://127.0.0.1:8000/). I see the page of Laravel and I dont know how to see the Ticket application. I tested changing die url to http://127.0.0.1:8000/Ticket but result is Not Found.

How I can see the working Ticket application?

Regards

MS

**Comment by krekas** [comment]
Learn basics first. How routing works

**Comment by fc-admin1** [comment]
> Learn basics first. How routing works

Ok. But that is a general answer. Can you not tell me easily the way to run the app? I would like to see a working project.

Thanks

MS

**Comment by krekas** [comment]
No. You need to create a user first, log in, and a user must have a role. Routes are where every route is in laravel projects. You must learn basics before checking here.

**Comment by fc-admin1** [comment]
> No. You need to create a user first, log in, and a user must have a role. Routes are where every route is in laravel projects. You must learn basics before checking here.

Ok. thanks

**Comment by fc-admin1** [comment]
http://127.0.0.1:8000/login
